---
channel: edge
addons:
  ntopng:
    repository: litinoveweedle/hassio-addon-ntopng
    target: ntopng
    image: ghcr.io/litinoveweedle/{arch}-ntopng
  taptap:
    repository: litinoveweedle/hassio-addon-taptap
    target: taptap
    image: ghcr.io/litinoveweedle/{arch}-taptap

