# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  aarch64: "ghcr.io/hassio-addons/base/aarch64:17.2.2"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  amd64: "ghcr.io/hassio-addons/base/amd64:17.2.2"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  armhf: "ghcr.io/hassio-addons/base/armhf:17.2.2"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  armv7: "ghcr.io/hassio-addons/base/armv7:17.2.2"
  # renovate: datasource=github-releases depName=hassio-addon-base packageName=hassio-addons/addon-base versioning=semver
  i386: "ghcr.io/hassio-addons/base/i386:17.2.2"
  
args:
  BUILD_REPO: litinoveweedle/hassio-addons-dev
  BUILD_DESCRIPTION: "hassio taptap addon"
  # renovate: datasource=github-releases depName=taptap packageName=litinoveweedle/taptap versioning=semver
  TAPTAP_VERSION: 0.1.1
  # renovate: datasource=github-releases depName=taptap-mqtt packageName=litinoveweedle/taptap-mqtt versioning=semver
  TAPTAP_MQTT_VERSION: 0.0.4
  
