# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:17.2.2"
  amd64: "ghcr.io/hassio-addons/base/amd64:17.2.2"
  armhf: "ghcr.io/hassio-addons/base/armhf:17.2.2"
  armv7: "ghcr.io/hassio-addons/base/armv7:17.2.2"
  i386: "ghcr.io/hassio-addons/base/i386:17.2.2"
  
args:
  TAPTAP_VERSION: 0.1.1
  TAPTAP_MQTT_VERSION: 0.0.3
